#!/usr/bin/bash

# quick and dirty add tasks with a prompt

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
. "$script_dir/tkb.cfg"

read -p 'Task: ' TASK_TEXT
while [ ! -z "$TASK_TEXT" ]
do 
    $todo_sh a "$TASK_TEXT"
    read -p 'Task: ' TASK_TEXT
done;

tkb-gen

